name: Linux-Build

on: 
  # push代码时触发workflow
  push:
    # 忽略README.md
    paths-ignore:
      - 'image/*'
      - 'README.md'
      - 'LICENSE'
  # pull_request时触发workflow
  pull_request:
    # 忽略README.md
    paths-ignore:
      - 'image/*'
      - 'README.md'
      - 'LICENSE'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        submodules: 'recursive'
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.13.2
      with:
        version: 5.15.2
    - name: Build
      run: |
        mkdir build
        cd build
        qmake ..
        make -j2
